import exp from "express";
import "dotenv/config";
import authController from "./src/controllers/authController";
import userController from "./src/controllers/userController";
import postController from "./src/controllers/postController";
const app = exp();
app.use("/auth", authController);
app.use("/user", userController);
app.use("/post", postController);
app.listen(process.env.PORT, () => console.log(`See you at http::localhost:${process.env.PORT}`));
